#!/bin/bash
set -eu -o pipefail

SELF_DIR=$(cd $(dirname ${0}) && pwd -P)
SELF=${SELF_DIR}/$(basename ${0})

ARCH=$(../forklift/forklift run builtin common current osinfo -a)
# Use forklift to install the packages necessary to build winpty
${FORKLIFT} run builtin common current install "make" "gcc-g++" "mingw64-${ARCH}-gcc-g++"

pushd ${SELF_DIR}/.. >/dev/null 2>&1
./configure
make
make install
popd >/dev/null 2>&1
